---
- name: Converge
  hosts: all
  tasks:
    - name: "Include ansible-role-artifactory-pip"
      include_role:
        name: "ansible-role-artifactory-pip"
      vars:
        artifactory_base_url: https://artifactory.corp.mongodb.com
        artifactory_username: "{{ lookup('env', 'ARTIFACTORY_USERNAME') }}"
        artifactory_password: "{{ lookup('env', 'ARTIFACTORY_PASSWORD') }}"
